language: php

php:
  - 8.0
  - 7.3
  - 7.4

os: linux

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - yarn install

script:
  - yarn prod
  - vendor/bin/phpunit
