language: php
php:
  - 7.4
  
os: linux
  
services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE social_media;'
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate

branches:
  only:
  - travis

script:
  - vendor/bin/phpunit
